# Generated by Django 3.1.3 on 2021-01-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModels',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update_time')),
                ('buy_time', models.DateField(help_text='购买时间', null=True, verbose_name='buy_time')),
                ('category', models.CharField(help_text='类别', max_length=50, verbose_name='category')),
                ('product', models.CharField(help_text='消耗品', max_length=100, unique=True, verbose_name='product')),
                ('count', models.IntegerField(help_text='消耗数量', verbose_name='count')),
                ('price', models.IntegerField(help_text='价格', verbose_name='price')),
                ('use_time', models.IntegerField(help_text='使用时长', verbose_name='use_time')),
                ('pet_name', models.ForeignKey(help_text='所属宠物', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='pets.petsmodels')),
            ],
            options={
                'verbose_name': '宠物消耗品',
                'db_table': 'pets_consume',
            },
        ),
    ]
