# Generated by Django 3.1.3 on 2021-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodels',
            name='product',
            field=models.CharField(help_text='消耗品', max_length=100, verbose_name='product'),
        ),
    ]
