# Generated by Django 3.1.3 on 2021-01-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetsModels',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update_time')),
                ('name', models.CharField(help_text='名字', max_length=10, unique=True, verbose_name='name')),
                ('weight', models.TextField(help_text='当前体重', max_length=3, verbose_name='weight')),
                ('birthday', models.DateField(help_text='什么时候出生的', null=True, verbose_name='birthday')),
                ('varieties', models.TextField(help_text='什么样的品种', max_length=50, verbose_name='varieties')),
                ('color', models.TextField(help_text='什么颜色', max_length=20, verbose_name='color')),
            ],
            options={
                'verbose_name': '宠物信息表',
                'db_table': 'pets_data',
            },
        ),
    ]
